name: 'statsfm to markdown'
description: 'Displays your stats.fm top albums as linked images with tooltips in your GitHub profile README.'
author: 'teraha-dev'

inputs:
  statsfm_username:
    description: 'Your stats.fm username (required)'
    required: true
  display_limit:
    description: 'Maximum number of albums to display (max 50)'
    required: false
    default: '10'
  items_per_row:
    description: 'Number of albums to display per row'
    required: false
    default: '5'
  show_duration:
    description: 'Include playtime in the image tooltip (true/false)'
    required: false
    default: 'true'
  show_rank:
    description: 'Include ranking number in the image tooltip (true/false)'
    required: false
    default: 'true'
  time_range:
    description: 'Time range for top albums (weeks/months/lifetime)'
    required: false
    default: 'weeks'
  readme_path:
    description: 'Path to the README file to update'
    required: false
    default: 'README.md'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_STATSFM_USERNAME: ${{ inputs.statsfm_username }}
    INPUT_DISPLAY_LIMIT: ${{ inputs.display_limit }}
    INPUT_ITEMS_PER_ROW: ${{ inputs.items_per_row }}
    INPUT_SHOW_DURATION: ${{ inputs.show_duration }}
    INPUT_SHOW_RANK: ${{ inputs.show_rank }}
    INPUT_TIME_RANGE: ${{ inputs.time_range }}
    INPUT_README_PATH: ${{ inputs.readme_path }}

branding:
  icon: 'music'
  color: 'green'